### Site Settings ###
title               : Sophie Wohltjen
description         : >-
                      I'm an assistant professor of psychology at the University of Tennessee, Knoxville. 
                      I completed my post-doctoral work in the Psychology department at University of Wisconsin - Madison. 
                      I worked with <a href="https://www.niedenthalemotionslab.com/">Paula Niedenthal</a>. 
                      I completed my Ph.D. in Psychological and Brain Sciences at Dartmouth with 
                      <a href="http://www.wheatlab.com/">Thalia Wheatley</a>. I study what happens when 
                      people get "in sync" — and what happens when they don't. 
baseurl             : ""                     # Change to empty quotes if you are hosting your site at <your-username>.github.io directly
repository          : sophiewohltjen/sophiewohltjen@github.io     # Change to <your-username>/<your-username>.github.io (or remove it if you don't need remote projects)
remote_theme        : YoussefRaafatNasry/portfolYOU
open_new_tab        : true                            # Opens external URLs in new tab (works for posts, projects and navbar only)


### Plugins ###
plugins:
  - jemoji

### Assets? ###
assets: 
  disableHLJS: true 
  favicon: assets/favicon.ico 
  favicon16x16: assets/favicon16x16.png 
  favicon32x32: assets/favicon32x32.png 
  apple_touch_icon: assets/apple-touch-icon.png 


### Navbar Settings ###
nav_exclude:                                            # The following paths are excluded from navbar
  - pages/tags.html
  - pages/404.html
  - pages/index.md


### Author Info ###
author:
  name              : Sophie Wohltjen
  image             : assets/images/headshot2021.jpg
# behance           : your_username
# dribbble          : your_username
  email             : wohltjen@wisc.edu
# facebook          : your_username
  github            : sophiewohltjen
# gitlab            : your_username
# instagram         : your_username
# kaggle            : your_username
  linkedin          : sophie-wohltjen-9b12b351
# medium            : your_username
# soundcloud        : your_username
# spotify           : your_username
# stackoverflow     : your_user_id
# tumblr            : your_username.tumblr.com
# twitch            : your_username
  twitter           : sophiewohltjen
# vimeo             : your_username
# youtube           : your_channel_name
# keybase           : your_username
  googlescholar     : i4sQcEMAAAAJ&hl=en



### Posts ###
#permalink: /blog/:title


### Collections ###
collections:
  projects:
    output: true
    permalink: /projects/:name


### Disqus ###
disqus:
  shortname: your-short-name-disqus                     # Your website Shortname on disqus


### Analytics ###
analytics:
  enabled: false                                        # Set true to enable analytics
  google:
    tracking_id: your-google-tracking-id


### Buy me a coffee ###
# See https://www.buymeacoffee.com/
buymeacoffee:
  enabled: false
  username: your_username
  color: "#007bff"
  message: "Thank you for visiting."                    # Message to be displayed aside from the button for a few seconds.
  description: "Support me on Buy me a coffee!"


### Defaults for collections ###
defaults:
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "page"
  - scope:
      path: ""
      type: "posts"
    values:
      comments: false                                   # Set to true to enable disqus comments


### Exclude from processing ###
exclude:
  - README.md
  - CONTRIBUTING.md
  - LICENSE
  - "*.log"
